### PR TITLE
Fixed removing member after update its metadata

### LINKED ISSUE #34: Cluster member has not removed on shutdown when using updateMetadata.
Hello, I am using clustercube-cluster.

Cluster member has not removed on shutdown when using updateMetadata.

Cluster.shutdown method send member-remove gossip message to GossipProtocolImpl. Received gossip message processing is here.
https://github.com/scalecube/scalecube-cluster/blob/0a64d2f2629dbb884e40f2cc63fd6237d2b59b55/cluster/src/main/java/io/scalecube/cluster/gossip/GossipProtocolImpl.java#L125

Its shutdown message contains metadata, but remoteMembers not contains metadata.
List.remove method call Member.equals method, both messages not equals metadata.

Change this
---
.subscribe(remoteMember -> remoteMembers.removeIf(member -> remoteMember.id().equals(member.id()));

Test case works on eclipse
https://github.com/umishu/scalecube-test

### PR DESCRIPTION
**Pull request by segabriel**
Fixes #34

### CODE REVIEW

File: cluster/src/main/java/io/scalecube/cluster/gossip/GossipProtocolImpl.java [hunk 1]
```diff
@@ -136,6 +125,17 @@ public void start() {
             TimeUnit.MILLISECONDS);
   }
 
+  private void onEvent(MembershipEvent event) {
+    Member member = event.member();
+    if (event.isRemoved() || event.isUpdated()) {
```
Comment (artem-v) [inline cluster/src/main/java/io/scalecube/cluster/gossip/GossipProtocolImpl.java]: `event.isUpdated()` ? Why ?

File: cluster/src/main/java/io/scalecube/cluster/gossip/GossipProtocolImpl.java [hunk 2]
```diff
@@ -136,6 +125,17 @@ public void start() {
...
+      remoteMembers.removeIf(
+          that -> that.id().equals(member.id()) && that.address().equals(member.address()));
+    }
+    if (event.isAdded() || event.isUpdated()) {
```
Comment (artem-v) [inline cluster/src/main/java/io/scalecube/cluster/gossip/GossipProtocolImpl.java]: `event.isUpdated()` ? Why ?

**Comment by artem-v** [comment]
@segabriel I accidentally pressed _approved_  button,   but  plz take a note about comments , don't merge it
